import { NextResponse } from 'next/server';
import { auth } from '@/auth';
import { prisma } from '@/lib/prisma';
import type { PreviewProgramRequest, ProgramData } from '@/types/program';

export async function POST(request: Request) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = (await request.json()) as PreviewProgramRequest;
    const { generationData } = body;

    // Here you would call your AI service to generate the program
    // For now, we'll return a mock preview
    const preview: ProgramData = {
      programName: `${generationData.trainingPreferences.trainingGoal} Program`,
      programDescription: 'Program description will be generated by AI',
      phases: [
        {
          phase: 1,
          durationWeeks: 4,
          bodyComposition: {
            bodyFatPercentage: generationData.currentStats.bodyFatLow || 15,
            muscleMassDistribution: generationData.currentStats.muscleMassDistribution || 'balanced',
          },
          trainingPlan: {
            daysPerWeek: generationData.trainingPreferences.daysAvailable,
            workouts: [],
          },
          nutrition: {
            dailyCalories: 2000,
            macros: {
              protein: 150,
              carbs: 200,
              fats: 70,
            },
          },
          progressionProtocol: [
            'Progressive overload based on previous performance',
            'Increase weight when all sets are completed with good form',
          ],
        },
      ],
    };

    return NextResponse.json(preview);
  } catch (error) {
    console.error('Error generating program preview:', error);
    return NextResponse.json(
      { error: 'Failed to generate program preview' },
      { status: 500 }
    );
  }
} 